[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
proofcommerce = "GwhBjtoAfoenUgtNGr4iEpCGMke75bYHQ5vN5mqeWyem"

[programs.localnet]
proofcommerce = "GwhBjtoAfoenUgtNGr4iEpCGMke75bYHQ5vN5mqeWyem"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".local/keys/operator.json"

[scripts]
test = "pnpm test:chain"
